name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17', '1.18' ]
    name: Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Unit Tests
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v -cover -timeout 30s ./...
